---
- hosts: vagrant
  vars_files:
    - vars.yml

  roles:
    - ansible-role-mpop

  environment:
    PPP_CONFIG_DIR: "{{ ppp_config_dir }}"

  tasks:
    - name: create data directory
      file: dest={{ data_path }} state=directory
      tags:
        - getdata

    - name: retrieve data from the web
      get_url: url=https://www.dropbox.com/s/udztssl3z1by2v6/S1A_EW_GRDM_1SDH_20151210T044114_20151210T044214_008975_00CDDB_1468.SAFE.zip?dl=1
          dest="{{ data_path }}/S1A_EW_GRDM_1SDH_20151210T044114_20151210T044214_008975_00CDDB_1468.SAFE.zip" checksum=md5:782e40d79b62f94e34fe1dca0333b19d

      tags:
        - getdata

    - name: Unarchive Sentinel-1 data
      unarchive: src=/home/vagrant/data/S1A_EW_GRDM_1SDH_20151210T044114_20151210T044214_008975_00CDDB_1468.SAFE.zip
        dest={{ data_path }} copy=false
      tags:
        - unzipdata

    - name: Install Sentinel-1 configuration file
      git: repo=https://github.com/mitkin/mpop-configs.git dest="{{ ppp_config_dir }}" force=yes
      tags:
        - git

    - name: Install Sentinel-1 test script
      git: repo=https://gist.github.com/bd39922b52fd3646c17a.git dest={{ scripts_dir }} force=yes
      tags:
        - git

    - name: Run test script
      shell: "{{ python_interpreter }} {{ scripts_dir }}/sentinel1_example.py"
      tags:
        - test
