---
- hosts: vagrant
  remote_user: root
  sudo: yes
  vars_files:
    - vars.yml

  roles:
    - ansible-role-mpop

  tasks:

    - name: Test mpop import projector
      command: "{{ python_interpreter }} -c 'from mpop import projector'"
